// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/zulkan/kraicklist/domain"
)

// Searcher is an autogenerated mock type for the Searcher type
type Searcher struct {
	mock.Mock
}

// Search provides a mock function with given fields: query
func (_m *Searcher) Search(query string) ([]domain.Record, error) {
	ret := _m.Called(query)

	var r0 []domain.Record
	if rf, ok := ret.Get(0).(func(string) []domain.Record); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Record)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
